const myLibrary = [];

function Book(title, author, pages, read) {
    //the constructor - author, title, number of pages, read, id autogenerated
    this.title = title;
    this.author = author;
    this.pages = pages;
    this.read = read; 
    this.id = crypto.randomUUID();
    this.updateStatus = function() {
        this.read = !(this.read);
        console.log(this.read);
        displayLibrary();
    };
}

function addBookToLibrary(title, author, pages, read) {
    //take params, create a book then store it in the array
    const book = new Book(title, author, pages, read)
    myLibrary.push(book);
    displayLibrary();
}

function displayLibrary() {
    //loop through array myLibrary, display each book on page in card format
    const content = document.querySelector(".content");
    content.innerHTML = '';
    for (book of myLibrary) {
        //create new card
        const card = document.createElement("div");
        card.classList.add("card");
        card.setAttribute("data-id", book.id);

        //create card's child elements
        const title = document.createElement("h3");
        title.classList.add("bookTitle");
        title.textContent = book.title;

        const author = document.createElement("p");
        author.classList.add("bookAuthor");
        author.textContent = book.author;

        const pages = document.createElement("p");
        pages.classList.add("bookPages");
        pages.textContent = book.pages + " pages";
    
        const status = document.createElement("button");
        status.classList.add("bookStatus");
        if (book.read == true) {
            status.textContent = "Read";
        }
        else {
            status.textContent = "Unread";
        }
        const removeBookButton = document.createElement("button");
        removeBookButton.classList.add("removeBookButton");
        removeBookButton.textContent = "remove";

        //append card children to card
        card.appendChild(title);
        card.appendChild(author);
        card.appendChild(pages);
        card.appendChild(status);
        card.appendChild(removeBookButton);

        content.appendChild(card);
    }
    const removeBookButtons = document.querySelectorAll(".removeBookButton")
    removeBookButtons.forEach((item) =>
        item.addEventListener("click", () => {
            const bookId = item.parentElement.dataset.id;
            removeBook(bookId);
    }));

    const updateStatusButtons = document.querySelectorAll(".bookStatus");
    updateStatusButtons.forEach((item) =>
        item.addEventListener("click", () => {
            const bookId = item.parentElement.dataset.id;
            const index = myLibrary.findIndex(item => item.id == bookId)
            myLibrary[index].updateStatus();
        }));
}

const dialog = document.querySelector("#addBookModal");
const addBookButton = document.querySelector("#addBook");
const closeModal = document.querySelector("#closeModal");
const addBookForm = document.querySelector('form');

addBookButton.addEventListener("click", () => {
    dialog.showModal();
});

closeModal.addEventListener("click", () => {
    dialog.close();
}
);

addBookForm.addEventListener('submit', function (event) {
    event.preventDefault();

    const formData = new FormData(addBookForm);
    const title = formData.get("title");
    const author = formData.get("author");
    const pages = formData.get("pages");
    const status = formData.get("status");
    
    addBookToLibrary(title, author, pages, status);
    dialog.close();
});


function removeBook(bookId) {
    const index = myLibrary.findIndex(item => item.id === bookId);
    myLibrary.splice(index, 1);
    displayLibrary();
}


addBookToLibrary("War and Peace", "Leo Tolstoy", 1225, true);
addBookToLibrary("A Sand County Almanac", "Aldo Leopold", 240, false);
addBookToLibrary("Gravity's Rainbow", "Thomas Pynchon", 760, false);

displayLibrary();